##/make test runs theres commands
##if no "-I" no path/ before program.cc
test_eigen:
	g++ -I eigen-3.4.0/ eigen_test.cc
test_pid:
	g++ PID_test.cc
test_planner:
	g++ -I eigen-3.4.0/ planner_test.cc
	